### ISSUE TITLE
Add Online Interactive Demo

### ISSUE THREAD

**Issue by philsawicki** [Autodesk/sjson#4]
Hi! 

I believe that adding an interactive demo or a microsite would benefit the Project. People curious about the SJSON format or some features of the Parser could try it out online and see right away how it works.

As one of the main concerns when converting a file from one format to the other is the handling of Erros, having an online example surfacing the exceptions thrown by the Parser could reassure developers about its robustness.

I created a simple online demo to showcase the Parser's features: https://philsawicki.github.io/sjson

Let me know if you are interested in hosting such a feature (or if there are any branding/design concerns). I would be happy to create a Pull Request against the `gh-pages` branch.

_Example of how SJSON content is converted to JSON:_
![image](https://cloud.githubusercontent.com/assets/7603502/20652237/7685740c-b4c3-11e6-9eaf-973b24ed9897.png)

_Example of how `SyntaxErrors` are surfaced:_
![image](https://cloud.githubusercontent.com/assets/7603502/20652232/5ce08208-b4c3-11e6-8006-28a4879c8473.png)

**Comment by adskdave** [comment]
I love it, @adskjohn can we update this repo with the demo??

**Comment by philsawicki** [comment]
If you create a `gh-pages` branch on this Repo, I can submit a PR against it tonight (or you can just copy/paste my branch if that's easier for your workflow).

Let me know what would be best for you.

**Comment by adskdave** [comment]
hey @philsawicki i created the branch (sorry for the delay)

Feel free to pr against it.

**Comment by philsawicki** [comment]
Thanks @adskdave! No worries, we're all very busy.

Opened the PR against `gh-pages` to create the page.

**Comment by adskjohn** [comment]
Thanks @philsawicki!  Merged the PR and added a link in the description.

**Comment by philsawicki** [comment]
Thanks @adskjohn! :)
